services:
   db:
      image: postgres:latest
      restart: unless-stopped
      ports:
         - 5432:5432
      environment:
         POSTGRES_USER: user
         POSTGRES_PASSWORD: 1234
         POSTGRES_DB: chatgpt
      volumes: 
         - db:/var/lib/postgresql/data

volumes:
   db: